import { Table } from './table.model';
import {User, UserSocialNetwork} from '../types/user.type';
import {Role} from '../types/role.type';
import {Position} from '../types/position.type';
import {Payroll} from '../types/payroll.type';
import {SocialNetwork} from '../types/social.type';
import {Department} from '../types/department.type';
import {Skill} from '../types/skill.type';
import {Comment} from '../types/comment.type';
import {Tag} from '../types/tag.type';
import {Bonus} from '../types/bonus.type';
import {Expense} from '../types/expense.type';
import {Right} from '../types/right.type';
import {Wage} from '../types/wage.type';

export const usersTable = new Table<User>('users');
export const rolesTable = new Table<Role>('roles');
export const rightsTable = new Table<Right>('rights');
export const userRightTable = new Table('users_rights');
export const roleRightTable = new Table('roles_rights');
export const userRoleTable = new Table('users_roles');
export const positionsTable = new Table<Position>('positions');
export const wagesTable = new Table<Wage>('wages');
export const payrollsTable = new Table<Payroll>('payrolls');
export const socialNetworksTable = new Table<SocialNetwork>('social_networks');
export const userSocialNetworkTable = new Table<UserSocialNetwork>('users_social_networks');
export const departmentsTable = new Table<Department>('departments');
export const skillsTable = new Table<Skill>('skills');
export const userSkillTable = new Table('users_skills');
export const commentsTable = new Table<Comment>('comments');
export const tagsTable = new Table<Tag>('tags');
export const userTagTable = new Table('users_tags');
export const bonusesTable = new Table<Bonus>('bonuses');
export const userBonusTable = new Table('users_bonuses');
export const expensesTable = new Table<Expense>('expenses');
export const userExpenseTable = new Table('users_expenses');
